FROM haproxy:1.7
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg



#FROM nginx:alpine

#RUN rm /etc/nginx/conf.d/*

#COPY proxy.conf /etc/nginx/conf.d/
#COPY proxy.conf /etc/nginx/sites-enabled/proxy.conf
